FROM python:3.11.1

WORKDIR /test_Gamma

RUN pip install gunicorn==20.1.0

COPY requirements.txt .

RUN pip install -r requirements.txt --no-cache-dir

COPY . .

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "test_Gamma.wsgi"]